### ISSUE TITLE
Add typescript sources

### ISSUE THREAD

**Issue by andrenarchy** [andywer/key-store#1]
I can't find the typescript sources in the repo. It seems like lib/ was included instead of src/

**Comment by andrenarchy** [comment]
errm ok I'm wrong, sorry. But the d.ts files shouldn't be in the repo, right?

**Comment by andrenarchy** [comment]
Also: tsconfig.json references src/index.ts which doesn't exist.

**Comment by andywer** [comment]
Ooops. Will fix that. So why doesn't it throw an error? ... 🤔

**Comment by andywer** [comment]
But I don't see a way to tell `tsc` to only generate a definition file for the index file, it will always create a `store.d.ts`, too.

**Comment by andywer** [comment]
Should be fixed by #2.
